In [2]:
import pandas as pd

df = pd.read_csv("../data/flipkart_products.csv")

df.head()

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

In [2]:
df.columns

Index(['uniq_id', 'crawl_timestamp', 'product_url', 'product_name',
       'product_category_tree', 'pid', 'retail_price', 'discounted_price',
       'image', 'is_FK_Advantage_product', 'description', 'product_rating',
       'overall_rating', 'brand', 'product_specifications'],
      dtype='object')

In [3]:
df.head(1)

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   uniq_id                  20000 non-null  object
 1   crawl_timestamp          20000 non-null  object
 2   product_url              20000 non-null  object
 3   product_name             20000 non-null  object
 4   product_category_tree    20000 non-null  object
 5   pid                      20000 non-null  object
 6   retail_price             19922 non-null  float64
 7   discounted_price         19922 non-null  float64
 8   image                    19997 non-null  object
 9   is_FK_Advantage_product  20000 non-null  bool
 10  description              19998 non-null  object
 11  product_rating           20000 non-null  object
 12  overall_rating           20000 non-null  object
 13  brand                    14136 non-null  object
 14  product_specifications   19986 non-null  object
dtypes: bool(1), float64(2), object(12)
memory usage: 2.2+ MB

In [3]:
cols = [
    "product_name",
    "product_category_tree",
    "brand",
    "description"
]

for col in cols:
    print("\n\n======", col, "======")
    print(df[col].dropna().sample(5).values)

====== product_name ======
['Oxyglow Golden Glow Pearl Protein Shampoo & Fruit Massage Cream With Vitamin-E 200gm'
 'BlueStone The Fashion Finesse Yellow Gold Diamond 18 K Ring'
 "Ishin Designer Studio Women's A-line Dress"
 'Anuradha Art Silver Polished Brooch' 'WallDesign Small Vinyl Sticker']


====== product_category_tree ======
['["Clothing >> Kids\' Clothing >> Girls Wear >> Dresses & Skirts >> Dresses >> Cutecumber Dresses"]'
 '["Tools & Hardware >> Tools >> Gardening Tools >> Plant Containers & Sets >> Plant Container Sets"]'
 '["Clothing >> Men\'s Clothing >> Shirts >> Formal Shirts >> Keystone Formal Shirts"]'
 '["Automotive >> Accessories & Spare parts >> Car Interior & Exterior >> Car Interior >> Car Mats"]'
 '["Jewellery >> Necklaces & Chains >> Necklaces"]']


====== brand ======
['3a AUTOCARE' 'Italian Fashion' 'First Smart Deal' 'Allure Auto'
 'kasemantra']


====== description ======
["S4S Stylish Women's Push-up Bra\n                         Price: Rs. 289\n\t\t\t\t\n\t\t\tS4S Brings you a range of stylish and comfortable collection. Colour may slightly vary depending on your computer monitor setting.\nS4S Brings you a range of stylish and comfortable collection. Colour may slightly vary depending on your computer monitor setting."
 "Navaksha Necktie Men's  Combo\n                         Price: Rs. 756\n\t\t\t\t\n\t\t\tNavaksha is a fast growing Brand in Fashion Accessories like Neckties, Bow Ties, Cravats, Cufflinks, Suspenders etc and commited to provide quality products to meet customer's expectations.This Maroon Micro Fiber Tie with Pocket Square is made of good quality Micro Fiber fabric, suitable for both Formal and Party wear.\nNavaksha is a fast growing Brand in Fashion Accessories like Neckties, Bow Ties, Cravats, Cufflinks, Suspenders etc and commited to provide quality products to meet customer's expectations.This Maroon Micro Fiber Tie with Pocket Square is made of good quality Micro Fiber fabric, suitable for both Formal and Party wear."
 "Magiq Nice Merry Women's Push-up Bra - Buy Green Magiq Nice Merry Women's Push-up Bra For Only Rs. 280 Online in India. Shop Online For Apparels. Huge Collection of Branded Clothes Only at Flipkart.com"
 'Rockmantra Sea Evening Sean Ceramic Mug (5.5 l)\n                         Price: Rs. 199\n\t\t\t\t\n\t\t\tGive a thrilling yet fresh start to your day. An exclusive creation by Rockmantra, this mug features porcelain crafting ensuring the design stays permanent for years to come and making it a perfect pick to gift your loved ones too!Dishwasher and microwave safe. Product details and specifications :\rMaterial : Ceramic\rSize : 3.5" X 4"\nGive a thrilling yet fresh start to your day. An exclusive creation by Rockmantra, this mug features porcelain crafting ensuring the design stays permanent for years to come and making it a perfect pick to gift your loved ones too!Dishwasher and microwave safe. Product details and specifications :\rMaterial : Ceramic\rSize : 3.5" X 4"'
 "Oviyon Printed Men's Round Neck T-Shirt - Buy Black Oviyon Printed Men's Round Neck T-Shirt For Only Rs. 999 Online in India. Shop Online For Apparels. Huge Collection of Branded Clothes Only at Flipkart.com"]